### ISSUE TITLE
Some benchmark files missing

### ISSUE THREAD

**Issue by RaulFD-creator** [dzjxzyd/UniDL4BioPep#1]
Hi @dzjxzyd, my name is Raul Fernandez-Diaz. I am building a ML tool for predicting peptide bioactivities and wanted to benchmark it against UniDL4BioPep as I think it is the current SOTA using the same benchmarks that you reported in your paper. I noticed that the following data sets are missing:
- Training and testing splits from `14. Antibacterial AB`
- Testing from `16. Antiviral AV`
- Training and testing from `19. antioxidant_FRS`

I would really appreciate if you could upload the files with the training and testing data so that I can use the same splits you used.

Thanks beforehand,

**Comment by dzjxzyd** [comment]
Hi, Raul
I am so glad that you want to UniDL4BioPep as the benchmark. 
I have updated the datasets.

- For Training and testing from 19. antioxidant_FRS. Because the original dataset do not provide the training and test dataset separately. So, here I only provide the whole dataset. You can refer this [antioxidant_dataset used in UniDL4BioPep.xlsx](https://github.com/dzjxzyd/UniDL4BioPep/blob/main/19.%20antioxidant_FRS/antioxidant_dataset%20used%20in%20UniDL4BioPep.xlsx).  To be honest, in my testing, I use this dataset [antioxidant_total original dataset from original paper.xlsx](https://github.com/dzjxzyd/UniDL4BioPep/blob/main/19.%20antioxidant_FRS/antioxidant_total%20original%20dataset%20from%20original%20paper.xlsx), where the positive is labeled as 1 and negative is labeled as 0. If you want to use the same dataset split ransom state, you can refer to this file [antioxidant_ESM_CNN_universial_architecture_model.ipynb](https://github.com/dzjxzyd/UniDL4BioPep/blob/main/19.%20antioxidant_FRS/antioxidant_ESM_CNN_universial_architecture_model.ipynb).
- test dataset of 16. Antiviral AV is here [AV_test.xlsx](https://github.com/dzjxzyd/UniDL4BioPep/blob/main/16.%20AV%20Antiviral/AV_test.xlsx). Train dataset is here [AV_train.xlsx](https://github.com/dzjxzyd/UniDL4BioPep/blob/main/16.%20AV%20Antiviral/AV_train.xlsx)
- 14. Antibacterial AB. Train and test datasets are [AB_train.xlsx](https://github.com/dzjxzyd/UniDL4BioPep/blob/main/14.%20antibacterial%20AB/AB_train.xlsx) and [AB_test.xlsx](https://github.com/dzjxzyd/UniDL4BioPep/blob/main/14.%20antibacterial%20AB/AB_test.xlsx), respectively. 

Please note that in the datasets, positive is labeled as 0 and negative is labeled as 1.

Best regards,
Zhenjiao

**Comment by dzjxzyd** [comment]
In the previous READ_ME file, we mentioned that 19 antioxidant and 5 antimicrobial datasets are different, where positives are labeled as 1 and negatives are labeled as 0.
So far, we have updated all the datasets and unified them as positive 0 and negative 1.

**Comment by RaulFD-creator** [comment]
Perfect, thank you very much.
